### ISSUE TITLE
OscarTensorizer & Working Demo

### ISSUE THREAD

**Issue by tomasmadeira** [michelecafagna26/VinVL#1]
Hi,

I cannot find "from oscar.wrappers import OscarTensorizer" in the "https://github.com/microsoft/Oscar" repository.

Or do you suggest another tensorizer for:

"# This takes care of the preprocessing
tensorizer = OscarTensorizer(tokenizer=tokenizer, device=device)"

Also, do you have a working demo for captioning?

Thanks in advance!

**Comment by michelecafagna26** [comment]
Hi @tomasmadeira ,

Thanks for reaching out.
The repo contains a modified version of the original Oscar repo. The tensorizer is indeed [here](https://github.com/michelecafagna26/VinVL/blob/main/Oscar/oscar/wrappers/wrappers.py)

I'm not sure about the error that you get, but I think that you may be able to solve it by setting correctly your working directory to "Oscar/" .

About the demo, there isn't one online, but it's something I'll try to set up in the coming weeks.

If you still have the issue please follow up maybe with more details.

Thanks
